### ISSUE TITLE
Add tmpwatch cron job to backup instance

### ISSUE THREAD

**Issue by Jyrsa** [coderefinery/gitlab-openstack-deploy#5]
Old backups are not deleted. There needs to be a [tmpwatch](https://linux.die.net/man/8/tmpwatch) cron job for the backup directories. 

There should be a configurable option for the number of days.

**Comment by rlaurika** [comment]
Addressed by #13

**Comment by Jyrsa** [comment]
This has been addressed in #13 and #20 for the gitlab host and backup host respectively.
